### ISSUE TITLE
Git clone repo

### ISSUE THREAD

**Issue by kurac338** [clarkemw/moonlight-embedded-raspbian-docker#2]
Hello,

I am planning to try out your launcher addon. Before I do, I wanted to take a look at the source code.

I can see that you are still referencing the old (deprecated) moonlight-embedded [repository](https://github.com/clarkemw/moonlight-embedded-raspbian-docker/blob/6075682155dce95c9d962c86d5e6acc970058e47/Dockerfile#L28).

The new maintainer is @cgutman, and the repository is located [here](https://github.com/moonlight-stream/moonlight-embedded), with the latest moonlight-embedded release being 2.5.1 as of 2021-08-12.

I believe the build procedure is the same (and there are packages available too in his repository).

Do you plan to update the Dockerfile to reflect this?

**Comment by clarkemw** [comment]
Thanks for the notification.  Should have an update to the dockerfile reflecting this change (and an overhaul of the plugin) available soon.

**Comment by clarkemw** [comment]
Dockerfile and image on dockerhub are now updated to 2.5.1.  Working on some automation to check the https://github.com/moonlight-stream/moonlight-embedded repo for the latest release and update/rebuild accordingly but its not behaving. Hope to have that resolved soon.
